version: '3'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    networks:
      - my-network
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: institute_management_system
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-app-container:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-container
    environment:
      - DB_HOST=mysql-container
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
    container_name: spring-app-container
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - my-network
    ports:
      - "8181:8787"  # Map the exposed port from the Dockerfile

networks:
  my-network:
#    driver: bridge

volumes:
  mysql-data:
#    driver: local
